In [3]:
import numpy as np

# Crear Arreglos desde Listas de Python

Podemos crear un arreglo mediante la conversión directa de una lista o lista de listas:

In [1]:
my_list = [1,2,3] #lista en python
my_list


[1, 2, 3]

In [4]:
np.array(my_list) #conversion de una lista a arreglo mediante el metodo 'array'


array([1, 2, 3])

In [5]:
a = np.array(my_list) #se peude asignar a una variable
type(a) #tipo de dato


numpy.ndarray

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]] # Una lista de listas
my_matrix


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix) # conversion de una lista de listas a Matriz


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
b = np.array(my_matrix) # aasginar la conversion a una variable
type(b) # tipo de dato


numpy.ndarray

# Metodos integrados (Built-in Methods)

Existen muchas funciones para de generar arreglos
arange

Devuelve valores espaciados uniformemente dentro de un intervalo dado. Es muy parecida a la funcion range de las basicas de python.

In [9]:

# generar un arreglo de enteros desde 0 hasta 9, recordar que el valor final no se incluye
np.arange(0,10)  # arange(valor_inicial,valor_final-1)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11,2) ## arange(valor_inicial,valor_final-1,paso)


array([ 0,  2,  4,  6,  8, 10])

# zeros y ones

Generar arreglos de Ceros o Unos

In [12]:
np.zeros(3) # Generar un arreglo de ceros que contenga 3 elementos


array([0., 0., 0.])

In [13]:
np.zeros((5,5)) # Generar una matriz de ceros de 5 x 5 elementos


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(3) # Generar un arreglo de unos que contenga 3 elementos


array([1., 1., 1.])

In [15]:
np.ones((3,7)) # Generar una matriz de unos de 5 x 5 elementos


array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

# linspace

Devuelve números espaciados uniformemente durante un intervalo especificado.

In [17]:
# Generar 3 valores iniciando en 0 y terminando en 10 (incluyendolo)
np.linspace(0,10,10) # linspace(valor_inicial, valor_final, numero_de_elementos)


array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [18]:
# Generar 50 valores iniciando en 0 y terminando en 10 (incluyendolo)
np.linspace(0,10,50)



array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

# eye

Crea la matriz identidad

In [19]:
np.eye(4) # crea la matriz identidad de 4x4 elementos


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Numeros Aleatorios (Random)

Numpy tiene diferentes formas de crear arrelgos de numeros aleatorios, el modulo para realizar esto se llama Random:
rand

Crea un arreglo de la forma dada y rellenela con muestras aleatorias de una distribución uniforme sobre [0, 1).

In [20]:
# creacion de un arreglo de 2 elementos 1 una dimension
np.random.rand(2) #Los numeros aleatorios seran de una distribucion uniforme


array([0.31726426, 0.17932493])

In [66]:
# creacion de un arreglo de 5x5
np.random.rand(5,5) #Los numeros aleatorios seran de una distribucion uniforme


array([[0.53184275, 0.49360592, 0.89119772, 0.86777406, 0.44749582],
       [0.57523273, 0.23585792, 0.19370431, 0.96987862, 0.59127218],
       [0.14492703, 0.4519466 , 0.84951909, 0.16519242, 0.8154229 ],
       [0.90964325, 0.90646181, 0.6952086 , 0.70675829, 0.62685836],
       [0.43339071, 0.96557532, 0.46007612, 0.52512848, 0.36784539]])

# randn

Devuelve una muestra (o muestras) de la distribución “estándar normal”. A diferencia del rand que es uniforme:

In [21]:
# creacion de un arreglo de 2 elementos 1 una dimension
np.random.randn(2) #Los numeros aleatorios seran de una distribucion "estándar normal"


array([-1.68026667, -0.68187354])

In [68]:
# creacion de un arreglo de 5x5
np.random.randn(5,5) #Los numeros aleatorios seran de una distribucion "estándar normal"


array([[-2.47861459, -0.96771469,  1.13563928,  0.81996983,  0.29744838],
       [ 0.40384898,  0.68360963, -0.63727608,  2.07149002,  0.04556146],
       [-0.57741848,  0.05976092,  0.42901439,  0.73113149, -1.02600833],
       [ 0.37365266, -0.35417125, -0.83582809, -1.58575994, -0.42540557],
       [-1.48609044,  0.27982329,  0.10423678,  1.1170038 , -0.78450243]])

# randint

Entrega numeros enteros aleatorios desde inicio (inclusivo) hasta final (exclusivo).

In [26]:
np.random.randint(1,100) # Genera un numero aleatorio entre 1 y 99


65

In [31]:
np.random.randint(1,100,(10,2)) # Genera un arreglo de 10 elementos entre 1 y 99


array([[73, 18],
       [72, 35],
       [73, 88],
       [96, 47],
       [20, 36],
       [83,  7],
       [38, 25],
       [ 8,  4],
       [40, 88],
       [17, 45]])

 
 
 # Atributos y Metodos de los arreglos

In [33]:
import numpy as np
arr = np.arange(25) #Genera un arreglo de numeros enteros del 0 al 24
ranarr = np.random.randint(0,50,10) #Genera un arreglo de 10 elementosdel 0 al 49


In [34]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
ranarr


array([39, 31,  7, 21,  6,  4, 32, 17, 37, 23])

# Reshape

Devuelve una matriz que contiene los mismos datos con una nueva distribucion

In [36]:
# arr es un vector de 25 elementos y se convertira en una matriz de 5x5
arr.reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# max,min,argmax,argmin

Estos son métodos útiles para encontrar valores máximos o mínimos. O para encontrar el indice de su ubicacione usando argmin o argmax

In [38]:
ranarr


array([39, 31,  7, 21,  6,  4, 32, 17, 37, 23])

In [39]:
ranarr.max() # Valor maximo del arreglo


39

In [40]:
ranarr.argmax() # Posicion del valor maximo del arreglo (recordar que empieza en cero)


0

In [41]:
ranarr.min() # Valor minimo del arreglo


4

In [42]:
ranarr.argmin() # Posicion del valor maximo del arreglo (recordar que empieza en cero)


5

# Shape

Shape es un attribute que los arreglos tienen para definir sus dimensiones (No es metodo):

In [43]:
# Vector
arr.shape


(25,)

In [44]:
# Cambiando las dimensiones del arreglo para que sea una matriz
# de una sola dimension horizontal
arr.reshape(1,25)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [45]:
# Cambiando las dimensiones del arreglo para que sea una matriz
# de una sola dimension vertical
arr.reshape(25,1)


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [46]:
arr.reshape(25,1).shape


(25, 1)

# size

Numero de elementos en un arreglo

In [49]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d.size

9

# ndim

Numero de dimensiones del arreglo o matriz

In [50]:
arr_2d.ndim


2

# Indexacion y Seleccion en NumPy

Como indexar y seleccionar elementos o grupos de elementos de un arreglo (array)

In [51]:
#Creando un arreglo de ejemplo
arr = np.arange(0,11) # Generar un arreglo de enteros del 0 hasta el 10
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr.dtype # tipos de datos dentro del arreglo


dtype('int32')

# Indexación y Selección con corchetes

La forma más sencilla de elegir uno o algunos elementos de una matriz es similar a las listas de Python:

In [53]:
# Obtener un valor conociendo su indice (index)
arr[8]


8

In [54]:
#Obtener los valores en un rango [valor_inicial, valor_final -1]
arr[1:5]


array([1, 2, 3, 4])

In [55]:
#Obtener los valores en un rango [valor_inicial, valor_final -1]
arr[0:5]


array([0, 1, 2, 3, 4])

# Broadcasting (Difusion)

Los arreglos de Numpy difieren de una lista normal de Python en su capacidad de Broadcasting, qeu es asignar un valor a un rango de posiciones:

In [56]:
# definiendo un valor para todo un rango de posiciones (Broadcasting)
arr[0:5]=100 # Asignar el numero 100 a las pocisiones desde el 0 hasta el 4
arr


array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [57]:
#crear nuevamente el arreglo con el que estabamos trabajando
arr = np.arange(0,11)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
#NOTA importante en la seleccion de rangos (sclicing)
# los arreglos son mutables
slice_of_arr = arr[0:6]
slice_of_arr


array([0, 1, 2, 3, 4, 5])

In [59]:
#Cambiar todos los valores a 99
slice_of_arr[:]=99
slice_of_arr


array([99, 99, 99, 99, 99, 99])

Observe que los cambios tambien ocurren en el arreglo original

In [60]:
arr


array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Los datos no se copian, ¡es un puntero a el arreglo original! ¡Esto evita problemas de memoria!

In [61]:
# Para obtener una copia, se debe hacer explicito
arr = np.arange(0,11)
arr_copy = arr.copy()
arr_copy[:] = 99
arr_copy


array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [62]:
# Observe que el arreglo original no se modifico
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Indexacion de arreglos 2D (matrices)

El formato general es arr_2d[fila][col] o arr_2d[fila,col]. Se recomienda usar la notacion con la coma por claridad.#

In [63]:
# Creacion de una matriz de 3x3
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [64]:
#Indexando por filas
arr_2d[1] # Obtener la fila 1 (recordar que el indice de python empieza en 0)


array([20, 25, 30])

In [65]:
# El formato es **arr_2d[fila][col]** o **arr_2d[fila,col]**
# Obteniendo un elemento en especifico
arr_2d[1][0] # elemento de la fila 1 columna 0


20

In [66]:
# seleccion de rangos en arreglos 2D (slicing)

#dimensiones (2,2) desde la esquina superior derecha
arr_2d[:2,1:] # filas [0,1] y columnas 1 hasta el final


array([[10, 15],
       [25, 30]])

In [67]:
# fila de indice 2
arr_2d[2]


array([35, 40, 45])

In [68]:
# todos los elementos de las columnas que estan en la fila de posicion 2
arr_2d[2,:]


array([35, 40, 45])

# Indexacion especial

La indexación especial permite seleccionar filas o columnas enteras desordenadas

In [69]:
#Creando una matriz de zeros
arr2d = np.zeros((10,10))
arr2d


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [70]:
#Tamaño del arreglo
arr_length = arr2d.shape[1]
arr_length


10

In [73]:
# Creando una matriz con elementos que contienen el valor correspondiente a la posicion de la fila
for i in range(arr_length):
    arr2d[i] = i
    
arr2d


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

La indexacion especial permite:

In [74]:
# sacar las filas 2, 4 , 6, 8
arr2d[[2,4,6,8]] # observe el uso de los dobles corchetes


array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [75]:
#Permite cualquier orden
arr2d[[6,4,2,7]]


array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

# Ayudas para indexacion

La indexación de una matriz 2d puede ser un poco confusa al principio, especialmente cuando comienza a agregar pasos en la seleccion. Pruebe buscar imagenes en google con la parala NumPy indexing y encontrara ejemplos utiles como: 

![Alt text](af0031e07738e01a1dd4413c08f08e3f.png)

# Seleccion basados en operadores de comparacion

In [76]:
# creacion de un arreglo de enteros desde 0 hasta 10
arr = np.arange(1,11) # recordar que el ultimo valor no se incluye
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
arr > 4 # determinar cuales valores del arreglo son mayores que 4
# el resultado es un arreglo de Booleans


array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [78]:
bool_arr = arr>4 # creacion de arreglo de booleans


In [79]:
bool_arr


array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [80]:
# Seleccion de elementos usando un arreglo de Booleans
arr[bool_arr] # Solamente se retornan los elementos en los cuales las posiciones de bool_arr sean verdaderas


array([ 5,  6,  7,  8,  9, 10])

In [81]:
# Se puede hacer esta seleccion mucho mas rapida realizando la comparacion dentro de los corchetes
arr[arr>2] # Obtener los valores del arreglo mayores que 2


array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
x = 2 # se puede hacer usando una variable
arr[arr>x]


array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
x = 2 # se puede hacer usando una variable
arr[arr>x]


array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Concatenacion

In [84]:
# En una dimension
x = np.array([1, 2, 3]) # Vector de valores
y = np.array([3, 2, 1]) # Vector de valores
np.concatenate([x, y]) # Concatenacion


array([1, 2, 3, 3, 2, 1])

In [85]:
# En dos dimensiones de forma vertical
grid = np.array([[1, 2, 3],[4, 5, 6]])
np.concatenate([grid, grid])


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [24]:
# En dos dimensiones de forma vertical
grid = np.array([[1, 2, 3],[4, 5, 6]])
np.concatenate([grid, grid])


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [86]:
# En dos dimensiones de forma horizontal
grid = np.array([[1, 2, 3],[4, 5, 6]])
np.concatenate([grid, grid],axis=1)


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Operaciones con NumPy

Con las listas de python no se pueden realizar operaciones elemento a elemento, pero con NumPy si se puede realizar.

## Como es el comportamiento de las listas ante las siguientres operaciones:

In [87]:
# observar el comportamiento de las listas
lista = list(range(10))
lista


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [88]:
lista + lista # este procedimento lo que hace es concatenar las listas


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [89]:
x = 2
lista*x # este procedimento hace que se repita la lista x numero de veces


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# Aritmetica

Puede realizar fácilmente aritmética de matriz a matriz o aritmética de escalar con matriz.

In [90]:
import numpy as np # importar la libreria de NumPy
arr = np.arange(0,10) # crear un arreglo de 10 elementos
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
arr + arr # Suma elemento a elemento de los arreglos


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [94]:
# Suma de valores uno a uno con arreglos
aa = np.arange(5)
bb = np.arange(10) # este arreglo es mas grande que el anterios
aa+bb[:5] # deben tener el mismo tamaño para realizar la suma


array([0, 2, 4, 6, 8])

In [95]:
arr * arr # Multiplicacion elemento a elemento


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [96]:
arr - arr # Resta elemento a elemento


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [97]:
# Mensaje de advertencia si se presenta una division por cero, pero no hay error!
# solo se reemplazo por el valor nan
arr/arr # division elemento a elemento


C:\Users\William\AppData\Local\Temp\ipykernel_8200\3685496176.py:3: RuntimeWarning: invalid value encountered in divide
  arr/arr # division elemento a elemento


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [98]:
arr**3 # eleva al cubo cada elemento del arreglo


array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

# Funciones Universales de los arreglos

NumPy tiene integrado muchas funciones universales, que son esencialmente solo operaciones matemáticas que se pueden usar para realizar la operación en todo el arreglo. Las mas importantes son:

    Matematicas
    Trigonometria
    Funciones de comparacion
    Funciones de punto flotante


In [101]:
#Calcular la raiz cuadrada de cada elemento
np.sqrt(325)


18.027756377319946

In [102]:
#Calcular el exponencial (e^) de cada elemento
np.exp(arr)


array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [103]:
# Obtener el valor maximo como una funcion
np.max(arr) #lo mismo arr.max()


9

In [104]:
# Calcular el Sin de cada elemento
np.sin(arr)


array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [105]:
# Calcular el Logaritmo de cada elemento
np.log(arr)


C:\Users\William\AppData\Local\Temp\ipykernel_8200\1673722079.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [106]:
# Calcular el valor absoluto
np.abs(arr)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Estadistica

In [107]:
# Desviacion estandar
np.std(arr)


2.8722813232690143

In [43]:
# Promedio de los valores
np.mean(arr) 


4.5

In [44]:
# Media
np.median(arr)


4.5

In [45]:
# Varianza
np.var(arr)


8.25

# Operaciones de Matrices

In [108]:
#creacion de una matriz de ejemplo
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [110]:
# transpuesta de una matriz
arr_2d.T # tambien puede ser arr_2d.transpose()


array([[ 5, 20, 35],
       [10, 25, 40],
       [15, 30, 45]])

In [111]:
# Multiplicacion de matrices
a = np.array([1,4,3]) # vector = arreglo de 1 dimension
b = np.array([2,-1,5]) # vector = arreglo de 1 dimension
a@b


13

In [49]:
#Tambien puede ser de esta forma
np.dot(a,b)


13

In [50]:
# Producto Cruz
a = np.array([1,4,3]) # vector = arreglo de 1 dimension
b = np.array([2,-1,5]) # vector = arreglo de 1 dimensi
np.cross(a,b)


array([23,  1, -9])